"""Criacao tabela casa_produto

Revision ID: b8aeee9ad27e
Revises: f566c97d8e69
Create Date: 2023-10-18 19:14:54.815278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8aeee9ad27e'
down_revision = 'f566c97d8e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casa_produtos',
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('casa_id', sa.Integer(), nullable=True),
    sa.Column('quantidade_desejada', sa.Integer(), nullable=True),
    sa.Column('quantidade_real', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['casa_id'], ['casa.id'], name=op.f('fk_casa_produtos_casa_id_casa')),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], name=op.f('fk_casa_produtos_produto_id_produto'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('casa_produtos')
    # ### end Alembic commands ###
