"""Mudando o bd

Revision ID: e36843ff3981
Revises: b8aeee9ad27e
Create Date: 2023-10-18 19:55:55.302423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e36843ff3981'
down_revision = 'b8aeee9ad27e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('casa_produtos', schema=None) as batch_op:
        batch_op.alter_column('produto_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('quantidade_desejada',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('quantidade_real',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('casa_produtos', schema=None) as batch_op:
        batch_op.alter_column('quantidade_real',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('quantidade_desejada',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('produto_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
