"""Criacao tabela produto

Revision ID: f566c97d8e69
Revises: 4dd7d8f22a8d
Create Date: 2023-10-18 16:53:03.761594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f566c97d8e69'
down_revision = '4dd7d8f22a8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('createdByUserId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['createdByUserId'], ['user.id'], name=op.f('fk_produto_createdByUserId_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_produto'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')

    op.drop_table('produto')
    # ### end Alembic commands ###
